base_url = "https://mailshine.salt.gg"

[feeds."games"] # Canonical Feed Name
title = "Games" # For Display -- Title of each Digest
reddits = ["games", "pcgaming"]
num_items = 10
schedule = "45 7 * * *" # https://crontab.guru/#45_7_*_*_*

[feeds."pcgaming"] # Canonical Feed Name
title = "PC Gaming" # For Display -- Title of each Digest
reddits = ["pcgaming"]
num_items = 20
schedule = "45 7 * * *"

